site_name: My Docs
nav:
  - Home: index.md
#  - About: about.md
  - User Guide:
      - Installation: user/installation.md
  - API Documentation:
      - Entry Points and Handlers: api/entry.md

theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
